/**
 * JobResponse.ts - Data contracts for the FlowForge backend.
 * These interfaces ensure type safety when handling API responses.
 */

/**
 * Initial response after submitting a prompt.
 */
export interface GenerationResponse {
  prompt_id: string;      // The unique ID assigned by ComfyUI
  message: string;        // Confirmation message from FastAPI
  refined_prompt: string; // The technical tags generated by the LLM
}

/**
 * Status update during the polling process.
 */
export interface StatusResponse {
  status: 'pending' | 'processing' | 'finished' | 'error';
  image_url?: string;      // Present only when the job is finished
  error_details?: string; // Optional field for debugging failures
}